spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-young-night-417320.us-west-2.aws.neon.tech:5432/neondb
    username: nadasif
    password: ch3iKpsolaU7
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_schema: angular
